name: ML Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-cml@V3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/
    
    - name: Train
      run: |
        python train_regression.py
    - name: Evaluate
      run: |
        python evaluate.py
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "## Model Metrics" >> report.md
        cat metrics.txt >> report.md

        echo "## confusoion matrix" >> report.md
        echo "![confusion matrix](result.png)" >> report.md

        cal comment create report.md
